### PR TITLE
Validation setup

### PR DESCRIPTION
**Pull request by pshivraj**
This PR address #7 and adds Validation setup notebook to benchmark current implementation of matterport measured against mAP for predefined set of validation images .

### CODE REVIEW

**Comment by havanagrawal** [comment]
The title for each plot is below the plot and can be misleading for some of the middle plots. Can we fix this quickly, or should we just go ahead and merge?

**Comment by pshivraj** [comment]
> The title for each plot is below the plot and can be misleading for some of the middle plots. Can we fix this quickly, or should we just go ahead and merge?

There is one more fix around one of the images validation mAP not coming correctly which i need to fix, i'll update the PR with title and mAP fix. For now lets hold the merge.

**Comment by tejasmhos** [comment]
Merge for now. We'll look into it later.

**Comment by pshivraj** [comment]
@havanagrawal check the current commit, I have fixed the title issue and added additional image.

**Review by lmtoan — APPROVED** [review]
Thanks Puru. Just a cosmetic comment, I think the mAP line should be closer to its corresponding triplet plot to avoid confusion.

**Pull request merged**
