### PR TITLE
Editing the labeling Readme

### PR DESCRIPTION
**Pull request by tejasmhos**
Added Supervisely workflow to the labeling workflow Readme.

### CODE REVIEW

**Review by vivanvish — DISMISSED** [review]
The changes looks fine. You cab merge it in.

**Review by havanagrawal — CHANGES_REQUESTED** [review]
Three changes please:

1. Add links at the top (table of content style) to jump to LabelMe Workflow and Supervisely workflow
2. The Supervisely workflow steps seem to describe how to create bounding boxes, not masks. Could you please confirm if the masks are being created, and if so, explicitly show them as a screenshot?
3. You seem to have broken the fix for Step 10 made by @vivanvish for showing the png image Can you please make sure you pull the latest changes into your PR?

**Comment by tejasmhos** [comment]
I added an image that clearly shows the mask in my latest commit. Please have a look and suggest any changes if needed. Thanks!

**Comment by havanagrawal** [comment]
Perfect, can you (or @vivanvish) please fix the [image link](https://github.com/havanagrawal/clomask/pull/5/files#diff-3ef868616572fec280759aafa301c2e8R40) in Step 10 of the LabelMe workflow of this PR? We can then merge it in.

**Comment by tejasmhos** [comment]
Hi Havan, I've made all the requested changes to the readme. Please review and merge the pull request.

**Review by havanagrawal — APPROVED** [review]

**Pull request merged**
